version: '3.8'

services:
  ocelot:
    image: ocelotapi:v1
    container_name: ocelot_api_gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:80"  # Exposes Ocelot API gateway on port 5000
    volumes:
      - ./ocelot.json:/app/ocelot.json  # Mount Ocelot configuration file
    networks:
      - ocelot_network

networks:
   ocelot_network:
       driver: bridge